CREATE DATABASE IF NOT EXISTS checkin DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
CREATE USER 'checkin'@'%' IDENTIFIED BY 'servicerequest';
GRANT ALL PRIVILEGES ON checkin.* TO 'checkin'@'%';
FLUSH PRIVILEGES;
