/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckinPhoto extends org.jooq.impl.TableImpl<org.checkin.repository.repository.tables.records.CheckinPhotoRecord> {

	private static final long serialVersionUID = 435944468;

	/**
	 * The reference instance of <code>checkin.checkin_photo</code>
	 */
	public static final org.checkin.repository.repository.tables.CheckinPhoto CHECKIN_PHOTO = new org.checkin.repository.repository.tables.CheckinPhoto();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.checkin.repository.repository.tables.records.CheckinPhotoRecord> getRecordType() {
		return org.checkin.repository.repository.tables.records.CheckinPhotoRecord.class;
	}

	/**
	 * The column <code>checkin.checkin_photo.id</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.CheckinPhotoRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>checkin.checkin_photo.fitness_checkin_id</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.CheckinPhotoRecord, java.lang.Long> FITNESS_CHECKIN_ID = createField("fitness_checkin_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>checkin.checkin_photo.label</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.CheckinPhotoRecord, java.lang.String> LABEL = createField("label", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>checkin.checkin_photo.storage_name</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.CheckinPhotoRecord, java.lang.String> STORAGE_NAME = createField("storage_name", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false), this, "");

	/**
	 * The column <code>checkin.checkin_photo.type</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.CheckinPhotoRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>checkin.checkin_photo.size</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.CheckinPhotoRecord, java.lang.Integer> SIZE = createField("size", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>checkin.checkin_photo</code> table reference
	 */
	public CheckinPhoto() {
		this("checkin_photo", null);
	}

	/**
	 * Create an aliased <code>checkin.checkin_photo</code> table reference
	 */
	public CheckinPhoto(java.lang.String alias) {
		this(alias, org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO);
	}

	private CheckinPhoto(java.lang.String alias, org.jooq.Table<org.checkin.repository.repository.tables.records.CheckinPhotoRecord> aliased) {
		this(alias, aliased, null);
	}

	private CheckinPhoto(java.lang.String alias, org.jooq.Table<org.checkin.repository.repository.tables.records.CheckinPhotoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.checkin.repository.repository.Checkin.CHECKIN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.checkin.repository.repository.tables.records.CheckinPhotoRecord, java.lang.Long> getIdentity() {
		return org.checkin.repository.repository.Keys.IDENTITY_CHECKIN_PHOTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.checkin.repository.repository.tables.records.CheckinPhotoRecord> getPrimaryKey() {
		return org.checkin.repository.repository.Keys.KEY_CHECKIN_PHOTO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.checkin.repository.repository.tables.records.CheckinPhotoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.checkin.repository.repository.tables.records.CheckinPhotoRecord>>asList(org.checkin.repository.repository.Keys.KEY_CHECKIN_PHOTO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.checkin.repository.repository.tables.CheckinPhoto as(java.lang.String alias) {
		return new org.checkin.repository.repository.tables.CheckinPhoto(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.checkin.repository.repository.tables.CheckinPhoto rename(java.lang.String name) {
		return new org.checkin.repository.repository.tables.CheckinPhoto(name, null);
	}
}
