/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FitnessCheckin extends org.jooq.impl.TableImpl<org.checkin.repository.repository.tables.records.FitnessCheckinRecord> {

	private static final long serialVersionUID = -979843641;

	/**
	 * The reference instance of <code>checkin.fitness_checkin</code>
	 */
	public static final org.checkin.repository.repository.tables.FitnessCheckin FITNESS_CHECKIN = new org.checkin.repository.repository.tables.FitnessCheckin();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.checkin.repository.repository.tables.records.FitnessCheckinRecord> getRecordType() {
		return org.checkin.repository.repository.tables.records.FitnessCheckinRecord.class;
	}

	/**
	 * The column <code>checkin.fitness_checkin.id</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.FitnessCheckinRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>checkin.fitness_checkin.uid</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.FitnessCheckinRecord, java.lang.Long> UID = createField("uid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>checkin.fitness_checkin.review_passed</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.FitnessCheckinRecord, java.lang.Boolean> REVIEW_PASSED = createField("review_passed", org.jooq.impl.SQLDataType.BIT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>checkin.fitness_checkin.timestamp</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.FitnessCheckinRecord, java.sql.Timestamp> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>checkin.fitness_checkin.record</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.FitnessCheckinRecord, java.lang.String> RECORD = createField("record", org.jooq.impl.SQLDataType.VARCHAR.length(768), this, "");

	/**
	 * Create a <code>checkin.fitness_checkin</code> table reference
	 */
	public FitnessCheckin() {
		this("fitness_checkin", null);
	}

	/**
	 * Create an aliased <code>checkin.fitness_checkin</code> table reference
	 */
	public FitnessCheckin(java.lang.String alias) {
		this(alias, org.checkin.repository.repository.tables.FitnessCheckin.FITNESS_CHECKIN);
	}

	private FitnessCheckin(java.lang.String alias, org.jooq.Table<org.checkin.repository.repository.tables.records.FitnessCheckinRecord> aliased) {
		this(alias, aliased, null);
	}

	private FitnessCheckin(java.lang.String alias, org.jooq.Table<org.checkin.repository.repository.tables.records.FitnessCheckinRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.checkin.repository.repository.Checkin.CHECKIN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.checkin.repository.repository.tables.records.FitnessCheckinRecord, java.lang.Long> getIdentity() {
		return org.checkin.repository.repository.Keys.IDENTITY_FITNESS_CHECKIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.checkin.repository.repository.tables.records.FitnessCheckinRecord> getPrimaryKey() {
		return org.checkin.repository.repository.Keys.KEY_FITNESS_CHECKIN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.checkin.repository.repository.tables.records.FitnessCheckinRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.checkin.repository.repository.tables.records.FitnessCheckinRecord>>asList(org.checkin.repository.repository.Keys.KEY_FITNESS_CHECKIN_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.checkin.repository.repository.tables.FitnessCheckin as(java.lang.String alias) {
		return new org.checkin.repository.repository.tables.FitnessCheckin(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.checkin.repository.repository.tables.FitnessCheckin rename(java.lang.String name) {
		return new org.checkin.repository.repository.tables.FitnessCheckin(name, null);
	}
}
