/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WechatUser extends org.jooq.impl.TableImpl<org.checkin.repository.repository.tables.records.WechatUserRecord> {

	private static final long serialVersionUID = -1300985126;

	/**
	 * The reference instance of <code>checkin.wechat_user</code>
	 */
	public static final org.checkin.repository.repository.tables.WechatUser WECHAT_USER = new org.checkin.repository.repository.tables.WechatUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.checkin.repository.repository.tables.records.WechatUserRecord> getRecordType() {
		return org.checkin.repository.repository.tables.records.WechatUserRecord.class;
	}

	/**
	 * The column <code>checkin.wechat_user.id</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>checkin.wechat_user.wechat_uid</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.String> WECHAT_UID = createField("wechat_uid", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false), this, "");

	/**
	 * The column <code>checkin.wechat_user.enabled</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.Boolean> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.BIT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>checkin.wechat_user.nickname</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.String> NICKNAME = createField("nickname", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>checkin.wechat_user.avatar</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.String> AVATAR = createField("avatar", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>checkin.wechat_user.sex</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.Integer> SEX = createField("sex", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>checkin.wechat_user.province</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.String> PROVINCE = createField("province", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>checkin.wechat_user.city</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>checkin.wechat_user.country</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR.length(16), this, "");

	/**
	 * The column <code>checkin.wechat_user.union_id</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.String> UNION_ID = createField("union_id", org.jooq.impl.SQLDataType.VARCHAR.length(32), this, "");

	/**
	 * The column <code>checkin.wechat_user.description</code>.
	 */
	public final org.jooq.TableField<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(512), this, "");

	/**
	 * Create a <code>checkin.wechat_user</code> table reference
	 */
	public WechatUser() {
		this("wechat_user", null);
	}

	/**
	 * Create an aliased <code>checkin.wechat_user</code> table reference
	 */
	public WechatUser(java.lang.String alias) {
		this(alias, org.checkin.repository.repository.tables.WechatUser.WECHAT_USER);
	}

	private WechatUser(java.lang.String alias, org.jooq.Table<org.checkin.repository.repository.tables.records.WechatUserRecord> aliased) {
		this(alias, aliased, null);
	}

	private WechatUser(java.lang.String alias, org.jooq.Table<org.checkin.repository.repository.tables.records.WechatUserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.checkin.repository.repository.Checkin.CHECKIN, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.checkin.repository.repository.tables.records.WechatUserRecord, java.lang.Long> getIdentity() {
		return org.checkin.repository.repository.Keys.IDENTITY_WECHAT_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.checkin.repository.repository.tables.records.WechatUserRecord> getPrimaryKey() {
		return org.checkin.repository.repository.Keys.KEY_WECHAT_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.checkin.repository.repository.tables.records.WechatUserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.checkin.repository.repository.tables.records.WechatUserRecord>>asList(org.checkin.repository.repository.Keys.KEY_WECHAT_USER_PRIMARY, org.checkin.repository.repository.Keys.KEY_WECHAT_USER_IDX_WECHAT_USER_WECHAT_UID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.checkin.repository.repository.tables.WechatUser as(java.lang.String alias) {
		return new org.checkin.repository.repository.tables.WechatUser(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.checkin.repository.repository.tables.WechatUser rename(java.lang.String name) {
		return new org.checkin.repository.repository.tables.WechatUser(name, null);
	}
}
