/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckinPhoto implements java.io.Serializable {

	private static final long serialVersionUID = -290246057;

	private java.lang.Long    id;
	private java.lang.Long    fitnessCheckinId;
	private java.lang.String  label;
	private java.lang.String  storageName;
	private java.lang.String  type;
	private java.lang.Integer size;

	public CheckinPhoto() {}

	public CheckinPhoto(
		java.lang.Long    id,
		java.lang.Long    fitnessCheckinId,
		java.lang.String  label,
		java.lang.String  storageName,
		java.lang.String  type,
		java.lang.Integer size
	) {
		this.id = id;
		this.fitnessCheckinId = fitnessCheckinId;
		this.label = label;
		this.storageName = storageName;
		this.type = type;
		this.size = size;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getFitnessCheckinId() {
		return this.fitnessCheckinId;
	}

	public void setFitnessCheckinId(java.lang.Long fitnessCheckinId) {
		this.fitnessCheckinId = fitnessCheckinId;
	}

	public java.lang.String getLabel() {
		return this.label;
	}

	public void setLabel(java.lang.String label) {
		this.label = label;
	}

	public java.lang.String getStorageName() {
		return this.storageName;
	}

	public void setStorageName(java.lang.String storageName) {
		this.storageName = storageName;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.Integer getSize() {
		return this.size;
	}

	public void setSize(java.lang.Integer size) {
		this.size = size;
	}
}
