/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FitnessCheckin implements java.io.Serializable {

	private static final long serialVersionUID = 522513411;

	private java.lang.Long     id;
	private java.lang.Long     uid;
	private java.lang.Boolean  reviewPassed;
	private java.sql.Timestamp timestamp;
	private java.lang.String   record;

	public FitnessCheckin() {}

	public FitnessCheckin(
		java.lang.Long     id,
		java.lang.Long     uid,
		java.lang.Boolean  reviewPassed,
		java.sql.Timestamp timestamp,
		java.lang.String   record
	) {
		this.id = id;
		this.uid = uid;
		this.reviewPassed = reviewPassed;
		this.timestamp = timestamp;
		this.record = record;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getUid() {
		return this.uid;
	}

	public void setUid(java.lang.Long uid) {
		this.uid = uid;
	}

	public java.lang.Boolean getReviewPassed() {
		return this.reviewPassed;
	}

	public void setReviewPassed(java.lang.Boolean reviewPassed) {
		this.reviewPassed = reviewPassed;
	}

	public java.sql.Timestamp getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(java.sql.Timestamp timestamp) {
		this.timestamp = timestamp;
	}

	public java.lang.String getRecord() {
		return this.record;
	}

	public void setRecord(java.lang.String record) {
		this.record = record;
	}
}
