/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WechatUser implements java.io.Serializable {

	private static final long serialVersionUID = -423730163;

	private java.lang.Long    id;
	private java.lang.String  wechatUid;
	private java.lang.Boolean enabled;
	private java.lang.String  nickname;
	private java.lang.String  avatar;
	private java.lang.Integer sex;
	private java.lang.String  province;
	private java.lang.String  city;
	private java.lang.String  country;
	private java.lang.String  unionId;
	private java.lang.String  description;

	public WechatUser() {}

	public WechatUser(
		java.lang.Long    id,
		java.lang.String  wechatUid,
		java.lang.Boolean enabled,
		java.lang.String  nickname,
		java.lang.String  avatar,
		java.lang.Integer sex,
		java.lang.String  province,
		java.lang.String  city,
		java.lang.String  country,
		java.lang.String  unionId,
		java.lang.String  description
	) {
		this.id = id;
		this.wechatUid = wechatUid;
		this.enabled = enabled;
		this.nickname = nickname;
		this.avatar = avatar;
		this.sex = sex;
		this.province = province;
		this.city = city;
		this.country = country;
		this.unionId = unionId;
		this.description = description;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getWechatUid() {
		return this.wechatUid;
	}

	public void setWechatUid(java.lang.String wechatUid) {
		this.wechatUid = wechatUid;
	}

	public java.lang.Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(java.lang.Boolean enabled) {
		this.enabled = enabled;
	}

	public java.lang.String getNickname() {
		return this.nickname;
	}

	public void setNickname(java.lang.String nickname) {
		this.nickname = nickname;
	}

	public java.lang.String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(java.lang.String avatar) {
		this.avatar = avatar;
	}

	public java.lang.Integer getSex() {
		return this.sex;
	}

	public void setSex(java.lang.Integer sex) {
		this.sex = sex;
	}

	public java.lang.String getProvince() {
		return this.province;
	}

	public void setProvince(java.lang.String province) {
		this.province = province;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getUnionId() {
		return this.unionId;
	}

	public void setUnionId(java.lang.String unionId) {
		this.unionId = unionId;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}
}
