/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WechatUserDao extends org.jooq.impl.DAOImpl<org.checkin.repository.repository.tables.records.WechatUserRecord, org.checkin.repository.repository.tables.pojos.WechatUser, java.lang.Long> {

	/**
	 * Create a new WechatUserDao without any configuration
	 */
	public WechatUserDao() {
		super(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER, org.checkin.repository.repository.tables.pojos.WechatUser.class);
	}

	/**
	 * Create a new WechatUserDao with an attached configuration
	 */
	public WechatUserDao(org.jooq.Configuration configuration) {
		super(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER, org.checkin.repository.repository.tables.pojos.WechatUser.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Long getId(org.checkin.repository.repository.tables.pojos.WechatUser object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchById(java.lang.Long... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public org.checkin.repository.repository.tables.pojos.WechatUser fetchOneById(java.lang.Long value) {
		return fetchOne(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.ID, value);
	}

	/**
	 * Fetch records that have <code>wechat_uid IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchByWechatUid(java.lang.String... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.WECHAT_UID, values);
	}

	/**
	 * Fetch a unique record that has <code>wechat_uid = value</code>
	 */
	public org.checkin.repository.repository.tables.pojos.WechatUser fetchOneByWechatUid(java.lang.String value) {
		return fetchOne(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.WECHAT_UID, value);
	}

	/**
	 * Fetch records that have <code>enabled IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchByEnabled(java.lang.Boolean... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.ENABLED, values);
	}

	/**
	 * Fetch records that have <code>nickname IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchByNickname(java.lang.String... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.NICKNAME, values);
	}

	/**
	 * Fetch records that have <code>avatar IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchByAvatar(java.lang.String... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.AVATAR, values);
	}

	/**
	 * Fetch records that have <code>sex IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchBySex(java.lang.Integer... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.SEX, values);
	}

	/**
	 * Fetch records that have <code>province IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchByProvince(java.lang.String... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.PROVINCE, values);
	}

	/**
	 * Fetch records that have <code>city IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchByCity(java.lang.String... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.CITY, values);
	}

	/**
	 * Fetch records that have <code>country IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchByCountry(java.lang.String... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.COUNTRY, values);
	}

	/**
	 * Fetch records that have <code>union_id IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchByUnionId(java.lang.String... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.UNION_ID, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<org.checkin.repository.repository.tables.pojos.WechatUser> fetchByDescription(java.lang.String... values) {
		return fetch(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.DESCRIPTION, values);
	}
}
