/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckinPhotoRecord extends org.jooq.impl.UpdatableRecordImpl<org.checkin.repository.repository.tables.records.CheckinPhotoRecord> implements org.jooq.Record6<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -979466060;

	/**
	 * Setter for <code>checkin.checkin_photo.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>checkin.checkin_photo.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>checkin.checkin_photo.fitness_checkin_id</code>.
	 */
	public void setFitnessCheckinId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>checkin.checkin_photo.fitness_checkin_id</code>.
	 */
	public java.lang.Long getFitnessCheckinId() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>checkin.checkin_photo.label</code>.
	 */
	public void setLabel(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>checkin.checkin_photo.label</code>.
	 */
	public java.lang.String getLabel() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>checkin.checkin_photo.storage_name</code>.
	 */
	public void setStorageName(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>checkin.checkin_photo.storage_name</code>.
	 */
	public java.lang.String getStorageName() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>checkin.checkin_photo.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>checkin.checkin_photo.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>checkin.checkin_photo.size</code>.
	 */
	public void setSize(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>checkin.checkin_photo.size</code>.
	 */
	public java.lang.Integer getSize() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO.FITNESS_CHECKIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO.LABEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO.STORAGE_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO.SIZE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getFitnessCheckinId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLabel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getStorageName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getSize();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckinPhotoRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckinPhotoRecord value2(java.lang.Long value) {
		setFitnessCheckinId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckinPhotoRecord value3(java.lang.String value) {
		setLabel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckinPhotoRecord value4(java.lang.String value) {
		setStorageName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckinPhotoRecord value5(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckinPhotoRecord value6(java.lang.Integer value) {
		setSize(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CheckinPhotoRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CheckinPhotoRecord
	 */
	public CheckinPhotoRecord() {
		super(org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO);
	}

	/**
	 * Create a detached, initialised CheckinPhotoRecord
	 */
	public CheckinPhotoRecord(java.lang.Long id, java.lang.Long fitnessCheckinId, java.lang.String label, java.lang.String storageName, java.lang.String type, java.lang.Integer size) {
		super(org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO);

		setValue(0, id);
		setValue(1, fitnessCheckinId);
		setValue(2, label);
		setValue(3, storageName);
		setValue(4, type);
		setValue(5, size);
	}
}
