/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FitnessCheckinRecord extends org.jooq.impl.UpdatableRecordImpl<org.checkin.repository.repository.tables.records.FitnessCheckinRecord> implements org.jooq.Record5<java.lang.Long, java.lang.Long, java.lang.Boolean, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = 611138295;

	/**
	 * Setter for <code>checkin.fitness_checkin.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>checkin.fitness_checkin.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>checkin.fitness_checkin.uid</code>.
	 */
	public void setUid(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>checkin.fitness_checkin.uid</code>.
	 */
	public java.lang.Long getUid() {
		return (java.lang.Long) getValue(1);
	}

	/**
	 * Setter for <code>checkin.fitness_checkin.review_passed</code>.
	 */
	public void setReviewPassed(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>checkin.fitness_checkin.review_passed</code>.
	 */
	public java.lang.Boolean getReviewPassed() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>checkin.fitness_checkin.timestamp</code>.
	 */
	public void setTimestamp(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>checkin.fitness_checkin.timestamp</code>.
	 */
	public java.sql.Timestamp getTimestamp() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>checkin.fitness_checkin.record</code>.
	 */
	public void setRecord(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>checkin.fitness_checkin.record</code>.
	 */
	public java.lang.String getRecord() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.Boolean, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Long, java.lang.Long, java.lang.Boolean, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.checkin.repository.repository.tables.FitnessCheckin.FITNESS_CHECKIN.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return org.checkin.repository.repository.tables.FitnessCheckin.FITNESS_CHECKIN.UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return org.checkin.repository.repository.tables.FitnessCheckin.FITNESS_CHECKIN.REVIEW_PASSED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return org.checkin.repository.repository.tables.FitnessCheckin.FITNESS_CHECKIN.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.checkin.repository.repository.tables.FitnessCheckin.FITNESS_CHECKIN.RECORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getReviewPassed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getRecord();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FitnessCheckinRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FitnessCheckinRecord value2(java.lang.Long value) {
		setUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FitnessCheckinRecord value3(java.lang.Boolean value) {
		setReviewPassed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FitnessCheckinRecord value4(java.sql.Timestamp value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FitnessCheckinRecord value5(java.lang.String value) {
		setRecord(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FitnessCheckinRecord values(java.lang.Long value1, java.lang.Long value2, java.lang.Boolean value3, java.sql.Timestamp value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FitnessCheckinRecord
	 */
	public FitnessCheckinRecord() {
		super(org.checkin.repository.repository.tables.FitnessCheckin.FITNESS_CHECKIN);
	}

	/**
	 * Create a detached, initialised FitnessCheckinRecord
	 */
	public FitnessCheckinRecord(java.lang.Long id, java.lang.Long uid, java.lang.Boolean reviewPassed, java.sql.Timestamp timestamp, java.lang.String record) {
		super(org.checkin.repository.repository.tables.FitnessCheckin.FITNESS_CHECKIN);

		setValue(0, id);
		setValue(1, uid);
		setValue(2, reviewPassed);
		setValue(3, timestamp);
		setValue(4, record);
	}
}
