/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WechatUserRecord extends org.jooq.impl.UpdatableRecordImpl<org.checkin.repository.repository.tables.records.WechatUserRecord> implements org.jooq.Record11<java.lang.Long, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 920048615;

	/**
	 * Setter for <code>checkin.wechat_user.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>checkin.wechat_user.wechat_uid</code>.
	 */
	public void setWechatUid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.wechat_uid</code>.
	 */
	public java.lang.String getWechatUid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>checkin.wechat_user.enabled</code>.
	 */
	public void setEnabled(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.enabled</code>.
	 */
	public java.lang.Boolean getEnabled() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>checkin.wechat_user.nickname</code>.
	 */
	public void setNickname(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.nickname</code>.
	 */
	public java.lang.String getNickname() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>checkin.wechat_user.avatar</code>.
	 */
	public void setAvatar(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.avatar</code>.
	 */
	public java.lang.String getAvatar() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>checkin.wechat_user.sex</code>.
	 */
	public void setSex(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.sex</code>.
	 */
	public java.lang.Integer getSex() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>checkin.wechat_user.province</code>.
	 */
	public void setProvince(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.province</code>.
	 */
	public java.lang.String getProvince() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>checkin.wechat_user.city</code>.
	 */
	public void setCity(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.city</code>.
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>checkin.wechat_user.country</code>.
	 */
	public void setCountry(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.country</code>.
	 */
	public java.lang.String getCountry() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>checkin.wechat_user.union_id</code>.
	 */
	public void setUnionId(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.union_id</code>.
	 */
	public java.lang.String getUnionId() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>checkin.wechat_user.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>checkin.wechat_user.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Long, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row11<java.lang.Long, java.lang.String, java.lang.Boolean, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.WECHAT_UID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.ENABLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.NICKNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.AVATAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.SEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.PROVINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.UNION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return org.checkin.repository.repository.tables.WechatUser.WECHAT_USER.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getWechatUid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getEnabled();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getNickname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getAvatar();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getSex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getProvince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getUnionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value2(java.lang.String value) {
		setWechatUid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value3(java.lang.Boolean value) {
		setEnabled(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value4(java.lang.String value) {
		setNickname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value5(java.lang.String value) {
		setAvatar(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value6(java.lang.Integer value) {
		setSex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value7(java.lang.String value) {
		setProvince(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value8(java.lang.String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value9(java.lang.String value) {
		setCountry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value10(java.lang.String value) {
		setUnionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord value11(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WechatUserRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Boolean value3, java.lang.String value4, java.lang.String value5, java.lang.Integer value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.String value11) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WechatUserRecord
	 */
	public WechatUserRecord() {
		super(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER);
	}

	/**
	 * Create a detached, initialised WechatUserRecord
	 */
	public WechatUserRecord(java.lang.Long id, java.lang.String wechatUid, java.lang.Boolean enabled, java.lang.String nickname, java.lang.String avatar, java.lang.Integer sex, java.lang.String province, java.lang.String city, java.lang.String country, java.lang.String unionId, java.lang.String description) {
		super(org.checkin.repository.repository.tables.WechatUser.WECHAT_USER);

		setValue(0, id);
		setValue(1, wechatUid);
		setValue(2, enabled);
		setValue(3, nickname);
		setValue(4, avatar);
		setValue(5, sex);
		setValue(6, province);
		setValue(7, city);
		setValue(8, country);
		setValue(9, unionId);
		setValue(10, description);
	}
}
