/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Checkin extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1928331548;

	/**
	 * The reference instance of <code>checkin</code>
	 */
	public static final Checkin CHECKIN = new Checkin();

	/**
	 * No further instances allowed
	 */
	private Checkin() {
		super("checkin");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO,
			org.checkin.repository.repository.tables.FitnessCheckin.FITNESS_CHECKIN,
			org.checkin.repository.repository.tables.WechatUser.WECHAT_USER);
	}
}
