/**
 * This class is generated by jOOQ
 */
package org.checkin.repository.repository;

/**
 * Convenience access to all tables in checkin
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table checkin.checkin_photo
	 */
	public static final org.checkin.repository.repository.tables.CheckinPhoto CHECKIN_PHOTO = org.checkin.repository.repository.tables.CheckinPhoto.CHECKIN_PHOTO;

	/**
	 * The table checkin.fitness_checkin
	 */
	public static final org.checkin.repository.repository.tables.FitnessCheckin FITNESS_CHECKIN = org.checkin.repository.repository.tables.FitnessCheckin.FITNESS_CHECKIN;

	/**
	 * The table checkin.wechat_user
	 */
	public static final org.checkin.repository.repository.tables.WechatUser WECHAT_USER = org.checkin.repository.repository.tables.WechatUser.WECHAT_USER;
}
